// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// REQUIRES: wony-registered-target
// RUN: %clang --target=wony %s -emit-llvm -o - -S | FileCheck %s

// Check that we can connect clang from the driver (as opposed to cc1) all
// the way to assembly code.

// CHECK-LABEL: define dso_local void @empty(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:    ret void
//
void empty() {
}
