# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -run-pass=legalizer %s -o - -mtriple=wony--darwin -verify-machineinstrs | FileCheck %s

---
name: add16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0

    ; CHECK-LABEL: name: add16
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 11
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s16) = G_ADD [[C]], [[C]]
    ; CHECK-NEXT: $r1 = COPY [[ADD]](s16)
    ; CHECK-NEXT: RET_PSEUDO implicit $r1
    %0:_(s16) = G_CONSTANT i16 11
    %1:_(s16) = G_ADD %0, %0
    $r1 = COPY %1(s16)
    RET_PSEUDO implicit $r1

...
---
name: add32
tracksRegLiveness: true
body:             |
  bb.1:
    ; CHECK-LABEL: name: add32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 132
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[C]], [[C]]
    ; CHECK-NEXT: $d1 = COPY [[ADD]](s32)
    ; CHECK-NEXT: RET_PSEUDO implicit $d1
    %0:_(s32) = G_CONSTANT i32 132
    %1:_(s32) = G_ADD %0, %0
    $d1 = COPY %1(s32)
    RET_PSEUDO implicit $d1
...
