# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc %s -run-pass=wony-mandatory-postlegalizer-combiner -o - -mtriple wony--darwin | FileCheck %s
---
name: unmergeValues
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $d1

    ; CHECK-LABEL: name: unmergeValues
    ; CHECK: liveins: $d1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprb(<2 x s16>) = COPY $d1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:gprb(s16) = G_EXTRACT_VECTOR_ELT [[COPY]](<2 x s16>), [[C]](s16)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s16) = G_CONSTANT i16 1
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:gprb(s16) = G_EXTRACT_VECTOR_ELT [[COPY]](<2 x s16>), [[C1]](s16)
    ; CHECK-NEXT: $r1 = COPY [[EVEC]](s16)
    ; CHECK-NEXT: $r2 = COPY [[EVEC1]](s16)
    ; CHECK-NEXT: RET_PSEUDO implicit $r1, implicit $r2
    %0:gprb(<2 x s16>) = COPY $d1
    %1:gprb(s16),%2:gprb(s16) = G_UNMERGE_VALUES %0
    $r1 = COPY %1
    $r2 = COPY %2
    RET_PSEUDO implicit $r1, implicit $r2
...
