; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple wony--darwin -o - %s -global-isel=1 -global-isel-abort=1 -verify-machineinstrs | FileCheck %s

define i16 @loadi16(ptr %arg) {
; CHECK-LABEL: loadi16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ldr16 r1, r1, 0
; CHECK-NEXT:    ret
  %res = load i16, ptr %arg
  ret i16 %res
}

define i16 @loadi16PlusImm(ptr %arg) {
; CHECK-LABEL: loadi16PlusImm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ldr16 r1, r1, 4
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %arg, i16 4
  %res = load i16, ptr %addr
  ret i16 %res
}

define i16 @loadi16PlusOffset(ptr %arg, i16 %offset) {
; CHECK-LABEL: loadi16PlusOffset:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi16 r1, r1, r2
; CHECK-NEXT:    ldr16 r1, r1, 0
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %arg, i16 %offset
  %res = load i16, ptr %addr
  ret i16 %res
}

define i32 @loadi32(ptr %arg) {
; CHECK-LABEL: loadi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ldr32 d1, r1, 0
; CHECK-NEXT:    ret
  %res = load i32, ptr %arg
  ret i32 %res
}

define i32 @loadi32PlusImm(ptr %arg) {
; CHECK-LABEL: loadi32PlusImm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ldr32 d1, r1, 12
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %arg, i16 12
  %res = load i32, ptr %addr
  ret i32 %res
}

; Check that we don't fold immediate that are too big to fit
; in the encoding space.
define i32 @loadi32PlusTooBigImm(ptr %arg) {
; CHECK-LABEL: loadi32PlusTooBigImm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ldi16 r2, 27
; CHECK-NEXT:    addi16 r1, r1, r2
; CHECK-NEXT:    ldr32 d1, r1, 0
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %arg, i16 27
  %res = load i32, ptr %addr
  ret i32 %res
}
