; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel=1 -global-isel=1 %s -mtriple=wony--darwin -o - | FileCheck %s

; Test that we scalarize the vector add.
; In other words we should end up with 2 adds that
; feed into the same d register.
define void @scalarize(ptr %src, ptr %dst) {
; CHECK-LABEL: scalarize:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subsp sp, sp, 8
; CHECK-NEXT:    strsp32 d2, sp, 4 # 4-byte Folded Spill
; CHECK-NEXT:    strsp32 d3, sp, 0 # 4-byte Folded Spill
; CHECK-NEXT:    ldr32 d2, r1, 0
; CHECK-NEXT:    addi16 r6, r4, r4
; CHECK-NEXT:    addi16 r7, r5, r5
; CHECK-NEXT:    str32 d3, r2, 0
; CHECK-NEXT:    ldrsp32 d3, sp, 0 # 4-byte Folded Reload
; CHECK-NEXT:    ldrsp32 d2, sp, 4 # 4-byte Folded Reload
; CHECK-NEXT:    addsp sp, sp, 8
; CHECK-NEXT:    ret
  %val = load <2 x i16>, ptr %src
  %res = add <2 x i16> %val, %val
  store <2 x i16> %res, ptr %dst
  ret void
}
