// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -triple wony -emit-llvm %s -o - | FileCheck %s
// REQUIRES: wony-registered-target

// CHECK-LABEL: define dso_local i32 @widening_signed_multiply(
// CHECK-SAME: i16 noundef signext [[A:%.*]], i16 noundef signext [[B:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i16, align 2
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i16, align 2
// CHECK-NEXT:    store i16 [[A]], ptr [[A_ADDR]], align 2
// CHECK-NEXT:    store i16 [[B]], ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[A_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.wony.widening.smul(i16 [[TMP0]], i16 [[TMP1]])
// CHECK-NEXT:    ret i32 [[TMP2]]
//
int widening_signed_multiply(short a, short b) {
  return __builtin_wony_widening_smul(a, b);
}

// CHECK-LABEL: define dso_local i32 @widening_unsigned_multiply(
// CHECK-SAME: i16 noundef zeroext [[A:%.*]], i16 noundef zeroext [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i16, align 2
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i16, align 2
// CHECK-NEXT:    store i16 [[A]], ptr [[A_ADDR]], align 2
// CHECK-NEXT:    store i16 [[B]], ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[A_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.wony.widening.umul(i16 [[TMP0]], i16 [[TMP1]])
// CHECK-NEXT:    ret i32 [[TMP2]]
//
unsigned int widening_unsigned_multiply(unsigned short a, unsigned short b) {
  return __builtin_wony_widening_umul(a, b);
}
